### ISSUE TITLE
Use the mocks mechanism to create an HTML renderer

### ISSUE THREAD

**Issue by guilhermedelyra** [GCES-Pydemic/pydemic-ui#11]
**Description:**
---

Create a class that simplifies the HTML from streamlit apps.

**Acceptance Criteria:**
---

- [x] Add handler to simple elements
- [x] Add handler to dataframes
- [x] Add handler to charts

**Comment by WillAllmeida** [comment]
Using STLogger class, create a new class to generate HTML pages based on existing apps

**Comment by WillAllmeida** [comment]
Dataframe handlers were added to HTML Report class
