### ISSUE TITLE
Implement daily expiring cache with fasttrack

### ISSUE THREAD

**Issue by guilhermedelyra** [GCES-Pydemic/pydemic-ui#18]
**Description:**
---

Criar um mecanismo para agendar tarefas com resultados salvos em cache. Enquanto o cache não atualizar, enviar dados antigos para o usuário para evitar longas esperas.

**Acceptance Criteria:**
---

Testes unitários

**Comment by sammyzord** [comment]
Cache was finished in commit 740f5b8
