### ISSUE TITLE
Refactor project applications to use a class based API

### ISSUE THREAD

**Issue by guilhermedelyra** [GCES-Pydemic/pydemic-ui#9]
**Description:**
---

Refactor existing apps using the class SimpleApp

apps:

- [x] calc.py
- [x] forecast.py
- [x] model_info.py
- [x] playground.py
- [x] projections_br.py
- [x] projections.py
- [x] scenarios1.py
- [x] scenarios2.py
- [x] api_explorer.py

**Comment by WillAllmeida** [comment]
Actually, forecast and playground apps contain errors. Both need to be reviewed

**Comment by RCristyan** [comment]
All apps were refactored, despite some bugs on forecast and playground
